### ISSUE TITLE
Add a Platform Abstraction Layer

### ISSUE THREAD

**Issue by speigg** [mozilla/webxr-examples#1]
Currently, platform logic is dispersed throughout the polyfill code, in sections that are separated by if statements such as 

```js
                if(this._vrDisplay !== null){ // Using ARCore
			...
		} else if(ARKitWrapper.HasARKit()){ // Using ARKit
			...
		} else { 
                        ...
                }
```

I think a platform abstraction layer would simplify things. This platform abstraction can be associated with XRDisplays:

```js
XRDisplay {
   _platform: PlatformAbstraction;
}
```

The XRDisplay should be able to choose the platform, and Realities should use whichever platform is exposed by the XRDisplay (without having to know anything about the platform implementation). This will also make it much easier to extend the polyfill to work with new platforms (especially without having to modify Reality implementations).

**Comment by speigg** [comment]
Likewise, XRSession has a comment in `requestFrame`:

```
	requestFrame(callback){
		if(typeof callback !== 'function'){
			throw 'Invalid callback'
		}
		// TODO If ARKit is present, switch to using the ARKit watch callback
		return window.requestAnimationFrame(() => {
			const frame = this._createPresentationFrame()
			this._display._reality._handleNewFrame(frame)
			this._display._handleNewFrame(frame)
			callback(frame)
		})
	}
```
 
However, if the platform abstraction layer exposes a `requestAnimationFrame`, then the XRSession can simply be:

```js
	requestFrame(callback){
		if(typeof callback !== 'function'){
			throw 'Invalid callback'
		}
		return this._display._platform.requestAnimationFrame(() => {
			const frame = this._createPresentationFrame()
			this._display._reality._handleNewFrame(frame)
			this._display._handleNewFrame(frame)
			callback(frame)
		})
	}
```

**Comment by TrevorFSmith** [comment]
There's not enough commonality between platforms to make a standard abstraction. All of the internal code of the polyfill is just temporary until the UA implements it, so there's not much point in trying to expose an abstraction.
